server:
  port: 7070
spring:
  application:
    name: web-java-course
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate.ddl-auto: update

application:
  restclient:
    response-timeout: 1000
