openapi: 3.0.1
info:
  title: WEB Java course API documentation
  version: 0.0.1-SNAPSHOT
servers:
- url: http://localhost:7071
  description: Local server
paths:
  /api/v1/order/products/{id}:
    get:
      tags:
      - product-controller
      summary: Get one Product by id
      operationId: getOne
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Product received
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProductDto"
        "404":
          description: Product not found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProblemDetail"
    put:
      tags:
      - product-controller
      summary: Update/create Product
      operationId: update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductForm"
        required: true
      responses:
        "400":
          description: Passed form to update is not valid
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ConstraintViolationProblemDetails"
        "200":
          description: Product updated or created
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProductDto"
    delete:
      tags:
      - product-controller
      summary: Delete Product by id
      operationId: delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: Deleted
  /api/v1/order/orders/{id}:
    get:
      tags:
      - order-controller
      operationId: getOne_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/OrderDto"
    put:
      tags:
      - order-controller
      operationId: update_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderForm"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/OrderDto"
    delete:
      tags:
      - order-controller
      operationId: delete_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: No Content
  /api/v1/order/products:
    get:
      tags:
      - product-controller
      summary: Get all Products
      operationId: getAll
      responses:
        "200":
          description: Products received
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductDto"
    post:
      tags:
      - product-controller
      summary: Create new Product
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductForm"
        required: true
      responses:
        "201":
          description: Product created
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProductDto"
        "409":
          description: Conflict in unique fields
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProblemDetail"
        "400":
          description: Passed form to create is not valid
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ConstraintViolationProblemDetails"
  /api/v1/order/orders:
    get:
      tags:
      - order-controller
      operationId: getAll_1
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OrderDto"
    post:
      tags:
      - order-controller
      operationId: create_1
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderForm"
        required: true
      responses:
        "201":
          description: Created
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/OrderDto"
  /api/v1/order/categories:
    get:
      tags:
      - category-controller
      operationId: getAll_2
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CategoryDto"
    post:
      tags:
      - category-controller
      operationId: create_2
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CategoryForm"
        required: true
      responses:
        "201":
          description: Created
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CategoryDto"
  /api/v1/order/orders/statistics:
    get:
      tags:
      - order-controller
      operationId: getProductOrderingStatistics
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductOrderingStatisticsDto"
  /api/v1/order/cosmo-cats:
    get:
      tags:
      - cosmo-cat-controller
      operationId: getCosmoCats
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CosmoCatDto"
  /api/v1/order/categories/{name}:
    get:
      tags:
      - category-controller
      operationId: getOne_2
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CategoryDto"
    delete:
      tags:
      - category-controller
      operationId: delete_2
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        "204":
          description: No Content
  /api/v1/greetings:
    get:
      tags:
      - greeting-controller
      operationId: greet
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    ProductForm:
      required:
      - name
      - price
      type: object
      properties:
        name:
          maxLength: 2147483647
          minLength: 5
          type: string
        description:
          type: string
        price:
          maximum: 1000000
          minimum: 1
          type: number
    ConstraintViolationProblemDetails:
      type: object
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
        status:
          type: integer
          format: int32
        detail:
          type: string
        instance:
          type: string
          format: uri
        properties:
          type: object
          additionalProperties:
            type: object
        fieldDetails:
          type: array
          items:
            $ref: "#/components/schemas/ParamsViolationDetails"
    ParamsViolationDetails:
      type: object
      properties:
        fieldName:
          type: string
        reason:
          type: string
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    ProductDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        price:
          type: number
        categories:
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/Category"
    OrderForm:
      required:
      - productId
      type: object
      properties:
        id:
          type: integer
          format: int64
        productId:
          type: integer
          format: int64
        quantity:
          maximum: 100
          minimum: 1
          type: integer
          format: int32
    OrderDto:
      type: object
      properties:
        product:
          $ref: "#/components/schemas/ProductDto"
        quantity:
          type: integer
          format: int32
        timestamp:
          type: string
          format: date-time
    ProblemDetail:
      type: object
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
        status:
          type: integer
          format: int32
        detail:
          type: string
        instance:
          type: string
          format: uri
        properties:
          type: object
          additionalProperties:
            type: object
    CategoryForm:
      required:
      - name
      type: object
      properties:
        name:
          maxLength: 2147483647
          minLength: 5
          type: string
    CategoryDto:
      type: object
      properties:
        name:
          type: string
    ProductOrderingStatisticsDto:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        productName:
          type: string
        orderingCount:
          type: integer
          format: int32
    CosmoCatDto:
      type: object
      properties:
        name:
          type: string
        color:
          type: string
        breed:
          type: string
        description:
          type: string
